### ISSUE TITLE
Incorrect URL from Vue Themes?

### ISSUE THREAD

**Issue by awc737** [vuetifyjs/parallax-starter#10]
I came here from: https://vuetifyjs.com/en/layout/pre-made-themes

and expected to see a theme, CSS or something. Did the theme get moved?

Thanks

**Comment by nekosaur** [comment]
Came here how. What link did you click? This repo has the source code for the parallax demo.

**Comment by johnleider** [comment]
The issue board is exclusively for bugs. Please direct all questions to the official [Discord](https://chat.vuetifyjs.com) server.
