### ISSUE TITLE
Broke?

### ISSUE THREAD

**Issue by rlam3** [vuetifyjs/parallax-starter#3]
![screen shot 2017-10-05 at 7 13 18 am](https://user-images.githubusercontent.com/1154044/31226697-af300762-a99c-11e7-8d05-7fed9f552423.png)

**Comment by vwxyzjn** [comment]
@rlam3 Yes, I am working on a pull request

**Comment by vwxyzjn** [comment]
@rlam3 see pull request [0.16 dispaly bug fix](https://github.com/vuetifyjs/parallax-starter/pull/4). If you want a quick fix, basically use the tag ``<v-content>`` to wrap everything under ``<main>`` tag

**Comment by nekosaur** [comment]
Fixed in #4
