### ISSUE TITLE
[assets\section.jpeg] Lexical error on line 1.

### ISSUE THREAD

**Issue by waldandrade** [vuetifyjs/parallax-starter#8]
When i run 'vue init vuerifyjs/parallax-starter my-project' on Windows 10 

vue-cli · [assets\section.jpeg] Lexical error on line 1. Unrecognized text.
����EExif  II*      
----------^

**Comment by nekosaur** [comment]
Can you post the entire log?

**Comment by waldandrade** [comment]
Yes, i can

Em 7 de nov de 2017 9:17 AM, "Albert Kaaman" <notifications@github.com>
escreveu:

Can you post the entire log?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/vuetifyjs/parallax-starter/issues/8#issuecomment-342465322>,
or mute the thread

**Comment by waldandrade** [comment]
C:\Projects\Vue>vue init vuetifyjs/parallax-starter site_opti

  vue-cli · [assets\section.jpeg] Lexical error on line 1. Unrecognized text.
����EExif  II*      
----------^

**Comment by waldandrade** [comment]
How can i get the log?

**Comment by nekosaur** [comment]
I just updated the template. Please try using it again. It seems like one of the images was corrupt in some way.
